spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: merger-id
      auto-offset-reset: earliest
      topic: tomerge
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      #value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
